### PR TITLE
Fix error

### PR DESCRIPTION
**Pull request by revskill10**

### CODE REVIEW

**Comment by abernix** [comment]
Could you be more specific about what exactly the problem was that led you to this solution?  For example, what error message were you receiving and what version of Node.js were you trying to run this example in?

**Comment by revskill10** [comment]
Hi @abernix , i'm using Node v10.7.0, i got error when running `node index.js`
```internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'core-js/modules/es7.object.entries'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/revskill/Learning/graphql/graphql-server-example/node_modules/apollo-upload-server/lib/middleware.js:14:1)
```

**Comment by abernix** [comment]
Cloning this repository and running `npm install` followed by `npm start` should solve the problem.  I can't be sure how you've run into this problem, but I'm certain that this PR is not the correct solution.  Specifically because `core-js` is not a direct dependency of this application which doesn't need any of the polyfills that `core-js` supplies, since all of the functionality is supported natively in all currently-supported Node.js versions (8+).

On the other hand the `apollo-upload-server` package _does_ rely on a `core-js` module, but that dependency is properly declared in its `package.json` and thus you should find it already installed if you've done an `npm install` before running this app.

Happy to answer additional questions here in this thread (And please do report back if you can successfully `npm install` and then `npm start` this app — it should work!), but I'll close this PR as it's not the right solution.

Thanks for your contribution!

**Comment by abernix** [comment]
I just want to circle back to this and let you know that this _was_ a problem, though not a problem with this repository directly.

It was also reported in the `apollo-server` repository (https://github.com/apollographql/apollo-server/issues/1542) and is now fixed via https://github.com/apollographql/apollo-server/pull/1556, which shipped in `apollo-server@2.0.5`.

While the `package-lock.json` in this repository should make it unnecessary to update to `apollo-server@2.0.5` to solve this problem, I've gone ahead and updated it anyway via dea65e1ecddd91da2e52ad860149b2958566ef2e.

Thanks for reporting this and sorry I didn't catch onto the exact problem until later.

**Pull request closed without merging**
